### ISSUE TITLE
LabCAS RDF should have public data only

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/CancerDataExpo#15]
As the title says: LabCAS RDF should have public data only. Currently it has everything.

**Comment by nutjob4life** [comment]
@asitang here's what the RDF generator does to get all collections:
```python
solr = Solr(context.labcasSolrURL + '/collections', auth=(context.username, context.password))
results = solr.search(q='*:*', rows=999999)  # 😮 TODO This'll fail once we get to a million collections
```
What should the `q` be to get just public collections only?

**Comment by nutjob4life** [comment]
@yuliujpl if you have a moment,  could you look at the above ↑ What should `q` be?

**Comment by yuliujpl** [comment]
@nutjob4life, I would use "QAState":"Public"! However, not all collections have QAState on them so @asitang  @hoodriverheather  we may need to make sure all collections have QAState? Thanks!

**Comment by hoodriverheather** [comment]
@nutjob4life @yuliujpl We stopped using QAState and now only use the OwnerPrincipal.

**Comment by nutjob4life** [comment]
bae6b00bb0733daec927f08b989d62126e3a4f16 goes ahead and adds owner principal to the RDF so the portal will have to filter. Closing this.
